# Generated by Django 4.2.2 on 2023-07-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueNumber', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('imgSrc', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('issueNumber', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.section')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
