# Generated by Django 4.2.2 on 2023-07-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgSrc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
