# Generated by Django 4.2.2 on 2023-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_imgsrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoon',
            name='imgSrc',
        ),
        migrations.RemoveField(
            model_name='pdfissue',
            name='url',
        ),
        migrations.AddField(
            model_name='cartoon',
            name='img',
            field=models.ImageField(default='asdf', upload_to='cartoons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfissue',
            name='pdf',
            field=models.FileField(default='adf', upload_to='pdfIssues'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='imgSrc',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
    ]
