# Generated by Django 4.2.2 on 2023-07-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cartoon_imgsrc_remove_pdfissue_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imgSrc',
            new_name='img',
        ),
    ]
