# Generated by Django 4.2.2 on 2023-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_section_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
