# Generated by Django 4.2.2 on 2023-07-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfissue',
            name='title',
        ),
        migrations.AlterField(
            model_name='pdfissue',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
