# Generated by Django 4.2.2 on 2023-07-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_section_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sectionSlug',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.PROTECT, to='articles.section'),
            preserve_default=False,
        ),
    ]
