# Generated by Django 4.2.2 on 2023-07-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_sectionslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sectionSlug',
            new_name='section',
        ),
    ]
